FifthApp/learning_users/basic_app/urls.py
from django.urls import path
#from django.conf.urls import include
from basic_app import views

app_name='basic_app'

urlpatterns = [
    path('register',views.register, name='register'),
    path('user_login',views.user_login, name='user_login'),
]

FifthApp/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

FifthApp/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

FifthApp/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

FifthApp/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("YOU RE LOGGED IN!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered =True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                            {'user_form':user_form,
                            'profile_form': profile_form,
                            'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("SOMEONE TRIED TO LOGIN AND FAILED")
            print("username: {} and password: {}".format(username,password))
            return HttpResponse('invalid login details supplied')
    else:
        return render(request,'basic_app/login.html', {})

FifthApp/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li>
            <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
          </li>
          <li>
            <a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a>
          </li>
          <li>
            <a class="navbar-link" href="{% url 'basic_app:register' %}">REGISTER</a>
          </li>
          {% if user.is_authenticated %}
          <li>
            <a class="navbar-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <li>
            <a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a>
          </li>
          {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock%}
    </div>
  </body>
</html>

FifthApp/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>DJANGO FIFTH APP</h1>
</div>
{% endblock %}

FifthApp/learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>PLEASE LOGIN</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password" >

    <input type="submit" name="" value="Login">
  </form>
</div>
{% endblock %}

FifthApp/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  {% if registered%}
   <h1>THANK YOU FOR REGISTERING</h1>
   {% else %}
   <h1>REGISTER HERE!</h1>
   <form enctype="multipart/form-data" method="post" >
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
   </form>
  {% endif %}
</div>
{% endblock %}